### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by seabilwe** [kartoza/SAGTA#35]
Should make sure of the following

- [ ] The site is up and running - This will be fixed with Rizky when he deploys this later but for now we randoms check it.
- [ ] Ensure all templates are being printed properly - Currently there are some embarrassing little bugs with the map templates
- [ ] Address any new issues that are raised by Bridget or Brandon ie

**Comment by NyakudyaA** [comment]
Superseded by #14
